/* $Id: SessionServiceRemote.java 509 2012-09-20 14:43:25Z dobashi $
 * 作成日: 2006/01/20 14:30:11
 *
 */
package com.lavans.lacoder2.experimental.http.session;

import java.io.IOException;
import java.util.Map;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.lavans.lacoder2.experimental.http.session.net.SessionServerConnection;
import com.lavans.lacoder2.experimental.http.session.net.SessionServerConnectionManager;



/**
 * SessionServiceWebクラス。
 *
 * This is generated by lamen.
 */
public class SessionServiceRemote {
	/** ロガー。debug用 */
	private static Logger logger = LoggerFactory.getLogger(SessionServiceRemote.class.getName());

	/** singleton実体 */
	private static SessionServiceRemote instance = null;

	/** Apサーバーへの接続 */
	private SessionServerConnectionManager connectionPool = SessionServerConnectionManager.getInstance();

	/**
	 * コンストラクタ。
	 * Singletonのため呼び出し不可。
	 */
	protected SessionServiceRemote(){

	}

	/**
	 * インスタンス取得メソッド。
	 * @return
	 */
	public static SessionServiceRemote getInstance(){
		if(instance==null){
			instance = new SessionServiceRemote();
		}
		return instance;
	}

	/**
	 * getSession
	 */
	@SuppressWarnings("unchecked")
	public Map<String, Object> getRemoteSessionAttribute(String jvm, String sessionId) {
		SessionServerConnection con = null;
		Object result = null;
		try{
			con = connectionPool.getConnection(jvm);
		} catch (IOException e) {
			logger.debug("SessionConnection作成失敗。["+ jvm +"]");
			return null;
		}

		try{
			result = con.execute(
				SessionServiceLocal.class.getName(),		// クラス名
				"getRemoteSessionAttribute",				// メソッド名
				new Class[]{String.class},	// 引数の型
				new Object[]{sessionId}	// 引数
			);
		} catch (Exception e) {
			logger.error( "getRemoteSesionAttribute failed.", e);
		}

		return (Map<String, Object>)result;
	}
}

